# Generated by Django 4.0.4 on 2022-04-29 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_user_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avatar',
        ),
    ]
