# Generated by Django 4.0.4 on 2022-05-03 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_description_profile_bio_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='wii_fitchico.png', upload_to=''),
        ),
    ]
