# Generated by Django 4.0.4 on 2022-05-06 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='2.jpg', null=True, upload_to='avatar'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
