# Generated by Django 4.0.4 on 2022-05-07 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_rename_avatar_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='2.jpg', null=True, upload_to='avatares'),
        ),
    ]
