# Generated by Django 4.0.4 on 2022-04-22 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0002_alter_post_date_publication_alter_post_date_updated_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='date_publication',
            new_name='timestamp',
        ),
        migrations.RenameField(
            model_name='postview',
            old_name='date_stamp',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='post',
            name='date_updated',
        ),
    ]
