# Generated by Django 4.0.4 on 2022-04-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0003_rename_date_publication_post_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='logo-invert.svg', upload_to=''),
        ),
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='avatar-ali.png', upload_to=''),
        ),
    ]
