# Generated by Django 4.0.4 on 2022-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='gym-girls.jpg', upload_to=''),
        ),
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
