# Generated by Django 4.0.4 on 2022-05-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0016_alter_avatar_image_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='image',
            field=models.ImageField(blank=True, default='batman.png', null=True, upload_to=''),
        ),
    ]
