# Generated by Django 4.0.4 on 2022-05-04 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0022_rename_user_post_author_alter_avatar_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
